require.config({
    baseUrl:"/",
    paths:{
        'header':'/js/modules/header',
        'footer':'/js/modules/footer',
        'jquery':'/libs/jquery.min',
        'swiper':'/libs/swiper.min',
        'myswiper':'/js/modules/myswiper',
        'url':'/js/url',
        'template':'/libs/template-web'
    }
})